dj/urls.py
from django.conf.urls import url
from django.contrib import admin
from short_links.views import main, list, add_short_link, url_info, redir_to, del_short_link

urlpatterns = [
    url(r'^$', main, name='main'),
    url(r'^list/$', list, name='list'),
    url(r'^add_short_link/$', add_short_link, name='add_short_link'),
    url(r'^del_short_link/(?P<id>\d+)/$', del_short_link, name='del_short_link'),
    url(r'^url_info/(?P<id>\d+)/$', url_info, name='url_info'),
    url(r'^admin/', admin.site.urls),
    url(r"^(?P<short_url>[\d\w]+)/$", redir_to, name='redir_to'),
]

short_links/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

# Create your models here.


class ShortLink(models.Model):
    """
    Модель для хранения данных по коротким ссылкам
    """

    link_orig = models.CharField(u'Original Link', max_length=1024)
    link_short = models.CharField(u'Short Link', max_length=1024)
    created = models.DateTimeField(u'Date', auto_now_add=True)
    use = models.IntegerField(u'CntIntUse', default=0)

    def __unicode__(self):
        return u'{}->{}'.format(self.link_orig, self.link_short)

    class Meta:
        verbose_name = u'Short Url'
        verbose_name_plural = u'Short Urls'

short_links/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from django import forms
from models import ShortLink


class ShortUrlForm(ModelForm):
    """
    Form class for validate url
    """

    link_orig = forms.URLField(
        label=u'Url', max_length=200,
        error_messages={'required': u'Укажите url'},
        widget=forms.TextInput(
            attrs={'placeholder': 'http://example.com'}
        )
    )

    class Meta:
        model = ShortLink
        fields = ("link_orig",)

short_links/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect, HttpResponse, get_object_or_404, HttpResponseRedirect
from django.db.models import F
from models import ShortLink
from forms import ShortUrlForm
import simplejson as json
# Create your views here.


def main(request):
    form = ShortUrlForm()
    links = ShortLink.objects.all().order_by('-use', '-created')[:20]
    return render(request, 'index.html', {'links': links, 'form': form})


def list(request):
    links = ShortLink.objects.all().order_by('-use', '-created')
    return render(request, 'list.html', {'links': links})


def add_short_link(request):
    errors = {}
    if request.method == "POST":
        form = ShortUrlForm(request.POST)
        if form.is_valid():
            short_url = form.save(commit=False)
            short_url.save()
            errors['state'] = '/url_info/{}'.format(short_url.id)
            return HttpResponse(json.dumps(errors, sort_keys=True))
        else:
            errors.update(form.errors)
            return HttpResponse(json.dumps(errors, sort_keys=True))


def del_short_link(request, id):
    cur_url = get_object_or_404(ShortLink, id=id)
    cur_url.delete()
    return redirect('list')


def url_info(request, id):
    cur_url = get_object_or_404(ShortLink, id=id)
    return render(request, 'url_info.html', {'cur_url': cur_url})


def redir_to(request, short_url):
    cur_dst = get_object_or_404(ShortLink, link_short=short_url)
    cur_dst.use = F('use') + 1
    cur_dst.save()
    return HttpResponseRedirect(cur_dst.link_orig)

templates/base.html
{% load staticfiles %}
{% load customs %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>ShortUrls service</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="{% static "js/jquery.min.js" %}" type="text/javascript"></script>
    <script src="{% static "js/jquery.dataTables.js" %}" type="text/javascript"></script>
</head>
<body>
<div class="wrapper">
    <div class="header">
        <div id="menu" class="menu">
            <ul>
                <li><a class="menuBtn {% current request "^/$" %}" href="/">Главная</a></li>
                <li><a class="menuBtn {% current request "^/list/$" %}" href="/list">Список ссылок</a></li>
            </ul>
        </div>
    </div>
    <div class="main">
        {% block main %}
        {% endblock %}
    </div>
    <div class="footer">
        <hr>
        <p>&copy; 2017</p>
    </div>
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block main %}
    <script>
        $(document).ready(function(){
            $('#id_link_orig').focus();
            $('#create_short').submit(function(event){
              event.preventDefault();
              var msg = $('#create_short').serialize();
              $.ajax({
                  type: 'POST',
                  dataType: 'json',
                  url: 'add_short_link/',
                  data: msg,
                  success: function(data) {
                      if (data.state == undefined){
                          if ($('.data_error').length){
                              $('.data_error').removeClass('data_error');
                          }
                          var items = [];
                          $.each(data, function(key, val){
                              $('#id_' + key).toggleClass('data_error');
                              items.push('<li class=\"error_msg\">' + val + '</li>')
                          });
                          $('#errormsg').html(items.join(''));
                      }
                      else {
                          window.location = data.state;
                      }
                  },
                  error: function(xhr, str){
                      console.log('some errors: ' + xhr.responseCode);
                  }
              });
          });
        });
    </script>

    <div id="create_urls">
        <form id="create_short" class="create_short">
            <fieldset>
                <legend>Создать короткую ссылку</legend>
                <ul id="errormsg"></ul>
                {% csrf_token %}
                {% for field in form %}
                    {{ field }}
                {% endfor %}
                <input type="submit" value="Создать">
            </fieldset>
        </form>
    </div>
    <h1>ТОП 20 коротких ссылок</h1>
    {% include 'partials/_table.html'%}
{% endblock %}

templates/list.html
{% extends 'base.html' %}

{% block main %}
    <h1>Список коротких ссылок</h1>
    {% include 'partials/_table.html'%}
{% endblock %}

templates/partials/_table.html
    <script type="text/javascript" language="javascript" class="init">
	$(document).ready(function() {
		$('#links').dataTable({
		    "order": []
        });
	});
    </script>
    <table id="links" class="display cell-border">
	<thead>
		<tr>
			<th>Ссылка</th>
			<th>Короткая ссылка</th>
			<th>Дата добавления</th>
			<th>Кол-во переходов</th>
            <th>Общая информация</th>
            <th>Действия</th>
		</tr>
	</thead>
	<tbody>
		{% for link in links %}
			<tr>
                <td><a target="_blank" href="{{ link.link_orig }}">{{ link.link_orig }}</a></td>
                <td><a target="_blank" href="http://{{ request.META.HTTP_HOST }}/{{ link.link_short }}">http://{{ request.META.HTTP_HOST }}/{{ link.link_short }}</a></td>
                <td>{{ link.created }}</td>
                <td>{{ link.use }}</td>
                <td><a target="_blank" href="/url_info/{{ link.id }}">Показать</a></td>
                <td><a href="/del_short_link/{{ link.id }}">Удалить</a></td>
			</tr>
		{% endfor %}
	</tbody>
    </table>

templates/url_info.html
{% extends 'base.html' %}
{% block main %}
    <h1>Информация по короткой ссылке</h1>
    <table class="url_info">
        <tr><td>Оригинальная ссылка:</td><td><a target="_blank" href="{{ cur_url.link_orig }}">{{ cur_url.link_orig }}</a></td></tr>
        <tr><td>Короткая ссылка:</td><td><a target="_blank" href="http://{{ request.META.HTTP_HOST }}/{{ cur_url.link_short }}">http://{{ request.META.HTTP_HOST }}/{{ cur_url.link_short }}</a></td></tr>
        <tr><td>Время создания:</td><td>{{ cur_url.created }}</td></tr>
        <tr><td>Количество переходов:</td><td>{{ cur_url.use }}</td></tr>
    </table>
{% endblock %}